### ISSUE TITLE
Почему вы отдаете всю информацию о пользователе (включая пароль)

### ISSUE THREAD

**Issue by AlphaBeth** [PiMat-maker/Web-4#10]
https://github.com/PiMat-maker/Web-4/blob/dbb63e9fd102f991e50740459894e885ca683932/Backend/src/main/java/manager/UserManager.java#L57

То же самое относится к логину

**Comment by PiMat-maker** [comment]
Теперь отдаем только токен
https://github.com/PiMat-maker/Web-4/blob/73272038b3ac91e7a85b73930efda160582a8bd9/Backend/src/main/java/manager/UserManager.java#L56
