### ISSUE TITLE
А где, собственно, авторизация?

### ISSUE THREAD

**Issue by AlphaBeth** [PiMat-maker/Web-4#11]
https://github.com/PiMat-maker/Web-4/blob/dbb63e9fd102f991e50740459894e885ca683932/Backend/src/main/java/manager/UserManager.java#L62-L70

Не вижу никакой проверки пароля...

**Comment by PiMat-maker** [comment]
Проверка пароля происходит в UserFilter.
https://github.com/PiMat-maker/Web-4/blob/dbb63e9fd102f991e50740459894e885ca683932/Backend/src/main/java/filters/UserFilter.java#L57-L58
