### ISSUE TITLE
Всё, что касается работы с пользователями, выглядит максимально странно

### ISSUE THREAD

**Issue by AlphaBeth** [PiMat-maker/Web-4#12]
Либо используйте обычную http basic авторизацию с передачей логина и пароля в заголовке, либо нормально реализуйте авторизацию с использованием токенов (генерируйте случайный токен при каждом логине, храните все токены в базе, токены должны быть криптографически стойкими).

**Comment by AlphaBeth** [comment]
Либо делайте jwt.

**Comment by PiMat-maker** [comment]
Создаем токен при каждом логине пользователя и сохраняем токен в базе https://github.com/PiMat-maker/Web-4/blob/73272038b3ac91e7a85b73930efda160582a8bd9/Backend/src/main/java/manager/UserManager.java#L71-L72
