### ISSUE TITLE
Использовать Link из react router и connected-react-router для хранения состояния навигации

### ISSUE THREAD

**Issue by AlphaBeth** [PiMat-maker/Web-4#13]
https://github.com/PiMat-maker/Web-4/blob/cb05530ca4dbc6aab0188ee67774c6965ab09d84/Frontend/React/src/App.js#L31-L36

**Comment by PiMat-maker** [comment]
Заменено на Link https://github.com/PiMat-maker/Web-4/blob/73272038b3ac91e7a85b73930efda160582a8bd9/Frontend/React/src/App.js#L32-L41
