### ISSUE TITLE
Ваше приложение должно обмениваться данными и событиями НЕ через html разметку

### ISSUE THREAD

**Issue by AlphaBeth** [PiMat-maker/Web-4#14]
https://github.com/PiMat-maker/Web-4/blob/cb05530ca4dbc6aab0188ee67774c6965ab09d84/Frontend/React/src/Canvas.js#L19-L36

**Comment by PiMat-maker** [comment]
Полностью удалили данную часть кода, создали новую функцию, которая проверяет попадание точки в область
https://github.com/PiMat-maker/Web-4/blob/ce532b9856b1c37b8fc49f344f64ccbe8bfdceb1/Frontend/React/src/Canvas.js#L63-L74
