### ISSUE TITLE
Если вам ДЕЙСТВИТЕЛЬНО нужен html элемент, то используйте ref, а не поиск по идентификатору

### ISSUE THREAD

**Issue by AlphaBeth** [PiMat-maker/Web-4#15]
https://github.com/PiMat-maker/Web-4/blob/cb05530ca4dbc6aab0188ee67774c6965ab09d84/Frontend/React/src/Canvas.js#L44

**Comment by PiMat-maker** [comment]
Изменили на ref https://github.com/PiMat-maker/Web-4/blob/43d19c145a053fa1b2e5a56c144e780d94e78ec2/Frontend/React/src/Canvas.js#L12-L15 https://github.com/PiMat-maker/Web-4/blob/43d19c145a053fa1b2e5a56c144e780d94e78ec2/Frontend/React/src/Canvas.js#L108
