### ISSUE TITLE
Пользователь уже загружен в фильтре

### ISSUE THREAD

**Issue by AlphaBeth** [PiMat-maker/Web-4#16]
https://github.com/PiMat-maker/Web-4/blob/b88f08c9eaf1de350c3545049ee0a6f264c84ab0/Backend/src/main/java/manager/FormManager.java#L38

Сохраните его в атрибуты запроса и потом просто сравните имена пользователей

**Comment by PiMat-maker** [comment]
https://github.com/PiMat-maker/Web-4/blob/b318311abfad793b25740f728d6d981b78ec4a21/Backend/src/main/java/manager/FormManager.java#L29-L31
