### ISSUE TITLE
А новый токен точно сохраняется?

### ISSUE THREAD

**Issue by AlphaBeth** [PiMat-maker/Web-4#17]
https://github.com/PiMat-maker/Web-4/blob/b88f08c9eaf1de350c3545049ee0a6f264c84ab0/Backend/src/main/java/manager/UserManager.java#L72

**Comment by PiMat-maker** [comment]
Теперь точно. https://github.com/PiMat-maker/Web-4/blob/2782417a93e8c4daeadfcd851023315018606da6/Backend/src/main/java/entities/DataBase.java#L52-L55

**Comment by PiMat-maker** [comment]
Теперь точно
https://github.com/PiMat-maker/Web-4/blob/b318311abfad793b25740f728d6d981b78ec4a21/Backend/src/main/java/entities/DataBase.java#L52-L56
