### ISSUE TITLE
Либо используйте нормальное логирование с правильным выбором уровня фильтрации, либо удалите

### ISSUE THREAD

**Issue by AlphaBeth** [PiMat-maker/Web-4#3]
https://github.com/PiMat-maker/Web-4/blob/dbb63e9fd102f991e50740459894e885ca683932/Backend/src/main/java/filters/UserFilter.java#L31

В других местах тоже

**Comment by PiMat-maker** [comment]
Удалены. cb05530ca4dbc6aab0188ee67774c6965ab09d84

**Comment by AlphaBeth** [comment]
Не удалены, повсюду в коде println

**Comment by PiMat-maker** [comment]
Теперь вроде удалены
