### ISSUE TITLE
Два запроса в бд там, где достаточно одного

### ISSUE THREAD

**Issue by AlphaBeth** [PiMat-maker/Web-4#4]
https://github.com/PiMat-maker/Web-4/blob/dbb63e9fd102f991e50740459894e885ca683932/Backend/src/main/java/filters/UserFilter.java#L54-L55

**Comment by PiMat-maker** [comment]
Сделан один запрос к бд. cb05530ca4dbc6aab0188ee67774c6965ab09d84
