### ISSUE TITLE
Получается, один пользователь может добавить точки другому?

### ISSUE THREAD

**Issue by AlphaBeth** [PiMat-maker/Web-4#6]
https://github.com/PiMat-maker/Web-4/blob/dbb63e9fd102f991e50740459894e885ca683932/Backend/src/main/java/manager/FormManager.java#L27

По-моему, так быть не должно

**Comment by PiMat-maker** [comment]
Все точки добавляются в одну бд с именем пользователя. Точки получаем из бд по имени пользователя, поэтому значения одного пользователя не появятся у другого.

**Comment by AlphaBeth** [comment]
У вас один авторизованный пользователь может добавлять точки ЛЮБОМУ другому, если сформирует правильный запрос на сервер.

**Comment by PiMat-maker** [comment]
Добавлена проверка токена для пользователя. Если токен не совпадает с сохраненным в бд токеном пользователя, которому мы хотим добавить точки, то выбрасываем ошибку
https://github.com/PiMat-maker/Web-4/blob/3729c6ef4ec0a7be9042e32b79a5b791bad75483/Backend/src/main/java/manager/FormManager.java#L27-L34
https://github.com/PiMat-maker/Web-4/blob/3729c6ef4ec0a7be9042e32b79a5b791bad75483/Backend/src/main/java/manager/FormManager.java#L38-L39
