### ISSUE TITLE
Съехало форматирование

### ISSUE THREAD

**Issue by AlphaBeth** [PiMat-maker/Web-4#9]
https://github.com/PiMat-maker/Web-4/blob/dbb63e9fd102f991e50740459894e885ca683932/Backend/src/main/java/manager/FormManager.java#L54-L62

**Comment by PiMat-maker** [comment]
Пофиксили. https://github.com/PiMat-maker/Web-4/blob/73272038b3ac91e7a85b73930efda160582a8bd9/Backend/src/main/java/manager/FormManager.java#L48-L56
